-- Optimized Supabase Schema for Startpage Bookmarks
-- Run this single script to set up your database properly

-- Drop existing table and constraints if they exist
DROP TABLE IF EXISTS bookmarks CASCADE;

-- Create the bookmarks table
CREATE TABLE bookmarks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT NOT NULL DEFAULT 'default_user',
  bookmarks_data JSONB NOT NULL DEFAULT '[]'::jsonb,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Add unique constraint for user_id
ALTER TABLE bookmarks
ADD CONSTRAINT unique_user_bookmarks UNIQUE (user_id);

-- Disable Row Level Security (required for anon key access)
ALTER TABLE bookmarks DISABLE ROW LEVEL SECURITY;

-- Create function to update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE 'plpgsql';

-- Create trigger to automatically update updated_at
CREATE TRIGGER update_bookmarks_updated_at
    BEFORE UPDATE ON bookmarks
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- Create index for better performance
CREATE INDEX idx_bookmarks_user_id ON bookmarks(user_id);

-- Create index for JSONB queries
CREATE INDEX idx_bookmarks_data ON bookmarks USING GIN (bookmarks_data);

-- Insert default data for testing (optional)
INSERT INTO bookmarks (user_id, bookmarks_data) 
VALUES ('default_user', '[
  {"title": "Hacker News", "url": "https://news.ycombinator.com", "chord": "HN"},
  {"title": "GitHub", "url": "https://github.com", "chord": "GH"},
  {"title": "Reddit", "url": "https://reddit.com", "chord": "RD"},
  {"title": "YouTube", "url": "https://youtube.com", "chord": "YT"},
  {"title": "Twitter", "url": "https://twitter.com", "chord": "TW"},
  {"title": "Wikipedia", "url": "https://wikipedia.org", "chord": "WK"}
]'::jsonb)
ON CONFLICT (user_id) DO NOTHING;

-- Verify table creation
SELECT 
  tablename, 
  schemaname,
  hasindexes,
  hasrules,
  hastriggers
FROM pg_tables 
WHERE schemaname = 'public' AND tablename = 'bookmarks';